env:
  commonjs: true
  es6: true
  node: true

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'prettier/@typescript-eslint'
  - 'plugin:prettier/recommended'

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2015
  sourceType: module

plugins:
  - '@typescript-eslint'
  - prettier

rules:
  no-console: 1
  no-debugger: 1
  no-var: 2
  eqeqeq: 2
  no-cond-assign: 2
  no-undef: 2
  prettier/prettier: 2
  no-unused-vars: 0
  '@typescript-eslint/no-unused-vars': 2
